function REC = importSubjDataRECWEBtable(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   DATA1 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   DATA1 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   data1 = importfile('data (1).csv', 2, 238);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/04/19 16:44:26

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,4,5,7,8,9,10,11,14]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,4,5,7,8,9,10,11,14]);
rawCellColumns = raw(:, [3,6,12,13,15,16,17]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
REC = table;
REC.rt = cell2mat(rawNumericColumns(:, 1));
REC.key_press = cell2mat(rawNumericColumns(:, 2));
REC.trial_type = rawCellColumns(:, 1);
REC.trial_index = cell2mat(rawNumericColumns(:, 3));
REC.time_elapsed = cell2mat(rawNumericColumns(:, 4));
REC.internal_node_id = rawCellColumns(:, 2);
REC.subject = cell2mat(rawNumericColumns(:, 5));
REC.group = cell2mat(rawNumericColumns(:, 6));
REC.stimulus = cell2mat(rawNumericColumns(:, 7));
REC.subject_key_press = cell2mat(rawNumericColumns(:, 8));
REC.acc = cell2mat(rawNumericColumns(:, 9));
REC.correct = rawCellColumns(:, 3);
REC.stimType = rawCellColumns(:, 4);
REC.stimOutput = cell2mat(rawNumericColumns(:, 10));
REC.response = rawCellColumns(:, 5);
REC.block = rawCellColumns(:, 6);
REC.correct_key_press = rawCellColumns(:, 7);

%% Tailoring the Table
REC = REC(~strcmp('',REC.block),:); % Delete empty rows




