function REC = importRECtable(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   REC = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   REC = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   REC = importfile('EmoNback_RECBehaviorABCD_20170224.csv', 2, 903);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/02/27 10:41:53

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using the
% specified date format.
try
    dates{5} = datetime(dataArray{5}, 'Format', 'dd-MMM-yyyy', 'InputFormat', 'dd-MMM-yyyy');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{5} = cellfun(@(x) x(2:end-1), dataArray{5}, 'UniformOutput', false);
        dates{5} = datetime(dataArray{5}, 'Format', 'dd-MMM-yyyy', 'InputFormat', 'dd-MMM-yyyy');
    catch
        dates{5} = repmat(datetime([NaN NaN NaN]), size(dataArray{5}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{5});
anyInvalidDates = isnan(dates{5}.Hour) - anyBlankDates;
dates = dates(:,5);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57]);
rawCellColumns = raw(:, [2,3,58,59]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
REC = table;
REC.ExperimentName = cell2mat(rawNumericColumns(:, 1));
REC.Site = rawCellColumns(:, 1);
REC.NDARGUID = rawCellColumns(:, 2);
REC.Version = cell2mat(rawNumericColumns(:, 2));
REC.SessionDate = dates{:, 1};
REC.Happy_HR = cell2mat(rawNumericColumns(:, 3));
REC.Happy_FA = cell2mat(rawNumericColumns(:, 4));
REC.Happy_Pr = cell2mat(rawNumericColumns(:, 5));
REC.Happy_Br = cell2mat(rawNumericColumns(:, 6));
REC.Happy_Miss = cell2mat(rawNumericColumns(:, 7));
REC.Happy_CR = cell2mat(rawNumericColumns(:, 8));
REC.Happy_dprime = cell2mat(rawNumericColumns(:, 9));
REC.Fear_HR = cell2mat(rawNumericColumns(:, 10));
REC.Fear_FA = cell2mat(rawNumericColumns(:, 11));
REC.Fear_Pr = cell2mat(rawNumericColumns(:, 12));
REC.Fear_Br = cell2mat(rawNumericColumns(:, 13));
REC.Fear_Miss = cell2mat(rawNumericColumns(:, 14));
REC.Fear_CR = cell2mat(rawNumericColumns(:, 15));
REC.Fear_dprime = cell2mat(rawNumericColumns(:, 16));
REC.Neut_HR = cell2mat(rawNumericColumns(:, 17));
REC.Neut_FA = cell2mat(rawNumericColumns(:, 18));
REC.Neut_Pr = cell2mat(rawNumericColumns(:, 19));
REC.Neut_Br = cell2mat(rawNumericColumns(:, 20));
REC.Neut_Miss = cell2mat(rawNumericColumns(:, 21));
REC.Neut_CR = cell2mat(rawNumericColumns(:, 22));
REC.Neut_dprime = cell2mat(rawNumericColumns(:, 23));
REC.Place_HR = cell2mat(rawNumericColumns(:, 24));
REC.Place_FA = cell2mat(rawNumericColumns(:, 25));
REC.Place_Pr = cell2mat(rawNumericColumns(:, 26));
REC.Place_Br = cell2mat(rawNumericColumns(:, 27));
REC.Place_Miss = cell2mat(rawNumericColumns(:, 28));
REC.Place_CR = cell2mat(rawNumericColumns(:, 29));
REC.Place_dprime = cell2mat(rawNumericColumns(:, 30));
REC.Happy0back_HR = cell2mat(rawNumericColumns(:, 31));
REC.Fear0back_HR = cell2mat(rawNumericColumns(:, 32));
REC.Neut0back_HR = cell2mat(rawNumericColumns(:, 33));
REC.Place0back_HR = cell2mat(rawNumericColumns(:, 34));
REC.Happy2back_HR = cell2mat(rawNumericColumns(:, 35));
REC.Fear2back_HR = cell2mat(rawNumericColumns(:, 36));
REC.Neut2back_HR = cell2mat(rawNumericColumns(:, 37));
REC.Place2back_HR = cell2mat(rawNumericColumns(:, 38));
REC.Happy_TargetHR = cell2mat(rawNumericColumns(:, 39));
REC.Happy_LureHR = cell2mat(rawNumericColumns(:, 40));
REC.Happy_NonlureHR = cell2mat(rawNumericColumns(:, 41));
REC.Fear_TargetHR = cell2mat(rawNumericColumns(:, 42));
REC.Fear_LureHR = cell2mat(rawNumericColumns(:, 43));
REC.Fear_NonlureHR = cell2mat(rawNumericColumns(:, 44));
REC.Neut_TargetHR = cell2mat(rawNumericColumns(:, 45));
REC.Neut_LureHR = cell2mat(rawNumericColumns(:, 46));
REC.Neut_NonlureHR = cell2mat(rawNumericColumns(:, 47));
REC.Place_TargetHR = cell2mat(rawNumericColumns(:, 48));
REC.Place_LureHR = cell2mat(rawNumericColumns(:, 49));
REC.Place_NonlureHR = cell2mat(rawNumericColumns(:, 50));
REC.ThreeExposure0backTargetStim = cell2mat(rawNumericColumns(:, 51));
REC.TwoExposure2backTargetStim = cell2mat(rawNumericColumns(:, 52));
REC.TwoExposure0backLureStim = cell2mat(rawNumericColumns(:, 53));
REC.TwoExposure2backLureStim = cell2mat(rawNumericColumns(:, 54));
REC.OneExposure0backStim = rawCellColumns(:, 3);
REC.OneExposure2backStim = rawCellColumns(:, 4);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% REC.SessionDate=datenum(REC.SessionDate);

