function webdata = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   DATA2 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   DATA2 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   data2 = importfile('data (2).csv', 1, 238);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/11 15:17:20

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));


%% Split data into numeric and cell columns.
rawNumericColumns = {};
rawCellColumns = raw(:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]);


%% Create output variable
webdata = raw;

%% Delete extraneous rows (fixation, attention checks), rename variables to fit conditiosn
blockcolumn = find(strcmp('block', webdata(1,:)));
rows2delete = find(strcmp('', webdata(:,blockcolumn)));
webdata(rows2delete,:) = [];
webdata(1, blockcolumn) = {'Block'};

stimcolumn = find(strcmp('stimType', webdata(1,:)));
rows2delete = find(strcmp('AttentionCheck', webdata(:,stimcolumn)));
webdata(rows2delete,:) = [];
webdata(1, stimcolumn) = {'StimType[Block]'};

rtcolumn = find(strcmp('rt', webdata(1,:)));
webdata(1, rtcolumn) = {'Stim.RT[Block]'};

acccolumn = find(strcmp('acc', webdata(1,:)));
webdata(1, acccolumn) = {'Stim.ACC[Block]'};

RESPcolumn = find(strcmp('subject_key_press', webdata(1,:)));
webdata(1, RESPcolumn) = {'Stim.RESP[Block]'};

outputcolumn = find(strcmp('stimOutput',webdata(1,:)));
webdata(1, outputcolumn) = {'Stimulus[Block]'};

