function subDataSST = importSubjDataSSTDecrepit(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   HYAENE6SST = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   HYAENE6SST = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   HYAENE6SST = importfile('2HYAENE6_SST.csv', 2, 368);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/27 14:02:21

%% Initialize variables.
delimiter = {'\t',','};
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[7,9,11,13,14,22,23,26,27,28,32,33,34,35,36,37,38,39,40,41,42,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,81,82,83,84,85,86,87,89,90,91,92,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

dateFormats = {'MM/dd/yyyy', 'HH:mm:ss'};
dateFormatIndex = 1;
blankDates = cell(1,size(raw,2));
anyBlankDates = false(size(raw,1),1);
invalidDates = cell(1,size(raw,2));
anyInvalidDates = false(size(raw,1),1);
for col=[18,20]% Convert the contents of columns with dates to MATLAB datetimes using the specified date format.
    try
        dates{col} = datetime(dataArray{col}, 'Format', dateFormats{col==[18,20]}, 'InputFormat', dateFormats{col==[18,20]}); %#ok<SAGROW>
    catch
        try
            % Handle dates surrounded by quotes
            dataArray{col} = cellfun(@(x) x(2:end-1), dataArray{col}, 'UniformOutput', false);
            dates{col} = datetime(dataArray{col}, 'Format', dateFormats{col==[18,20]}, 'InputFormat', dateFormats{col==[18,20]}); %%#ok<SAGROW>
        catch
            dates{col} = repmat(datetime([NaN NaN NaN]), size(dataArray{col})); %#ok<SAGROW>
        end
    end
    
    dateFormatIndex = dateFormatIndex + 1;
    blankDates{col} = cellfun(@isempty, dataArray{col});
    anyBlankDates = blankDates{col} | anyBlankDates;
    invalidDates{col} = isnan(dates{col}.Hour) - blankDates{col};
    anyInvalidDates = invalidDates{col} | anyInvalidDates;
end
dates = dates(:,[18,20]);
blankDates = blankDates(:,[18,20]);
invalidDates = invalidDates(:,[18,20]);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [7,9,11,13,14,22,23,26,27,28,32,33,34,35,36,37,38,39,40,41,42,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,81,82,83,84,85,86,87,89,90,91,92,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128]);
rawCellColumns = raw(:, [1,2,3,4,5,6,8,10,12,15,16,17,19,21,24,25,29,30,31,43,44,45,46,47,48,49,50,51,79,80,88,93,97]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
subDataSST = table;
subDataSST.ExperimentName = rawCellColumns(:, 1);
subDataSST.Subject = rawCellColumns(:, 2);
subDataSST.Session = rawCellColumns(:, 3);
subDataSST.Allowed = rawCellColumns(:, 4);
subDataSST.ClockInformation = rawCellColumns(:, 5);
subDataSST.DataFileBasename = rawCellColumns(:, 6);
subDataSST.DisplayRefreshRate = cell2mat(rawNumericColumns(:, 1));
subDataSST.ExperimentVersion = rawCellColumns(:, 7);
subDataSST.Group = cell2mat(rawNumericColumns(:, 2));
subDataSST.Handedness = rawCellColumns(:, 8);
subDataSST.leftarrow = cell2mat(rawNumericColumns(:, 3));
subDataSST.NARGUID = rawCellColumns(:, 9);
subDataSST.RandomSeed = cell2mat(rawNumericColumns(:, 4));
subDataSST.rightarrow = cell2mat(rawNumericColumns(:, 5));
subDataSST.RuntimeCapabilities = rawCellColumns(:, 10);
subDataSST.RuntimeVersion = rawCellColumns(:, 11);
subDataSST.RuntimeVersionExpected = rawCellColumns(:, 12);
subDataSST.SessionDate = dates{:, 1};
subDataSST.SessionStartDateTimeUtc = rawCellColumns(:, 13);
subDataSST.SessionTime = dates{:, 2};
subDataSST.StudioVersion = rawCellColumns(:, 14);
subDataSST.triggercode = cell2mat(rawNumericColumns(:, 6));
subDataSST.Block = cell2mat(rawNumericColumns(:, 7));
subDataSST.ProcedureBlock = rawCellColumns(:, 15);
subDataSST.RunningBlock = rawCellColumns(:, 16);
subDataSST.TestBlockA = cell2mat(rawNumericColumns(:, 8));
subDataSST.TestBlockACycle = cell2mat(rawNumericColumns(:, 9));
subDataSST.TestBlockASample = cell2mat(rawNumericColumns(:, 10));
subDataSST.TestBlockB = rawCellColumns(:, 17);
subDataSST.TestBlockBCycle = rawCellColumns(:, 18);
subDataSST.TestBlockBSample = rawCellColumns(:, 19);
subDataSST.Trial = cell2mat(rawNumericColumns(:, 11));
subDataSST.BeginFixDuration = cell2mat(rawNumericColumns(:, 12));
subDataSST.BeginFixDurationError = cell2mat(rawNumericColumns(:, 13));
subDataSST.BeginFixFinishTime = cell2mat(rawNumericColumns(:, 14));
subDataSST.BeginFixOffsetDelay = cell2mat(rawNumericColumns(:, 15));
subDataSST.BeginFixOffsetTime = cell2mat(rawNumericColumns(:, 16));
subDataSST.BeginFixOnsetDelay = cell2mat(rawNumericColumns(:, 17));
subDataSST.BeginFixOnsetTime = cell2mat(rawNumericColumns(:, 18));
subDataSST.BeginFixOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 19));
subDataSST.BeginFixStartTime = cell2mat(rawNumericColumns(:, 20));
subDataSST.CorrectAnswer = cell2mat(rawNumericColumns(:, 21));
subDataSST.EndFixDuration = rawCellColumns(:, 20);
subDataSST.EndFixDurationError = rawCellColumns(:, 21);
subDataSST.EndFixFinishTime = rawCellColumns(:, 22);
subDataSST.EndFixOffsetDelay = rawCellColumns(:, 23);
subDataSST.EndFixOffsetTime = rawCellColumns(:, 24);
subDataSST.EndFixOnsetDelay = rawCellColumns(:, 25);
subDataSST.EndFixOnsetTime = rawCellColumns(:, 26);
subDataSST.EndFixOnsetToOnsetTime = rawCellColumns(:, 27);
subDataSST.EndFixStartTime = rawCellColumns(:, 28);
subDataSST.FixDuration = cell2mat(rawNumericColumns(:, 22));
subDataSST.FixDurationError = cell2mat(rawNumericColumns(:, 23));
subDataSST.FixFinishTime = cell2mat(rawNumericColumns(:, 24));
subDataSST.FixOffsetDelay = cell2mat(rawNumericColumns(:, 25));
subDataSST.FixOffsetTime = cell2mat(rawNumericColumns(:, 26));
subDataSST.FixOnsetDelay = cell2mat(rawNumericColumns(:, 27));
subDataSST.FixOnsetTime = cell2mat(rawNumericColumns(:, 28));
subDataSST.FixOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 29));
subDataSST.FixRESP = cell2mat(rawNumericColumns(:, 30));
subDataSST.FixRT = cell2mat(rawNumericColumns(:, 31));
subDataSST.FixStartTime = cell2mat(rawNumericColumns(:, 32));
subDataSST.FixDur = cell2mat(rawNumericColumns(:, 33));
subDataSST.GoACC = cell2mat(rawNumericColumns(:, 34));
subDataSST.GoCRESP = cell2mat(rawNumericColumns(:, 35));
subDataSST.GoDuration = cell2mat(rawNumericColumns(:, 36));
subDataSST.GoDurationError = cell2mat(rawNumericColumns(:, 37));
subDataSST.GoFinishTime = cell2mat(rawNumericColumns(:, 38));
subDataSST.GoOffsetDelay = cell2mat(rawNumericColumns(:, 39));
subDataSST.GoOffsetTime = cell2mat(rawNumericColumns(:, 40));
subDataSST.GoOnsetDelay = cell2mat(rawNumericColumns(:, 41));
subDataSST.GoOnsetTime = cell2mat(rawNumericColumns(:, 42));
subDataSST.GoOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 43));
subDataSST.GoRESP = cell2mat(rawNumericColumns(:, 44));
subDataSST.GoRT = cell2mat(rawNumericColumns(:, 45));
subDataSST.GoRTTime = cell2mat(rawNumericColumns(:, 46));
subDataSST.GoStartTime = cell2mat(rawNumericColumns(:, 47));
subDataSST.Jitter = cell2mat(rawNumericColumns(:, 48));
subDataSST.ProcedureTrial = rawCellColumns(:, 29);
subDataSST.RunningTrial = rawCellColumns(:, 30);
subDataSST.SiemensPadOffsetDelay = cell2mat(rawNumericColumns(:, 49));
subDataSST.SiemensPadOffsetTime = cell2mat(rawNumericColumns(:, 50));
subDataSST.SiemensPadOnsetDelay = cell2mat(rawNumericColumns(:, 51));
subDataSST.SiemensPadOnsetTime = cell2mat(rawNumericColumns(:, 52));
subDataSST.SiemensPadOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 53));
subDataSST.SiemensPadRTTime = cell2mat(rawNumericColumns(:, 54));
subDataSST.SSDACC = cell2mat(rawNumericColumns(:, 55));
subDataSST.SSDCRESP = rawCellColumns(:, 31);
subDataSST.SSDDurationError = cell2mat(rawNumericColumns(:, 56));
subDataSST.SSDOnsetDelay = cell2mat(rawNumericColumns(:, 57));
subDataSST.SSDOnsetTime = cell2mat(rawNumericColumns(:, 58));
subDataSST.SSDOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 59));
subDataSST.SSDRESP = rawCellColumns(:, 32);
subDataSST.SSDRT = cell2mat(rawNumericColumns(:, 60));
subDataSST.SSDRTTime = cell2mat(rawNumericColumns(:, 61));
subDataSST.SSDDur = cell2mat(rawNumericColumns(:, 62));
subDataSST.Stimulus = rawCellColumns(:, 33);
subDataSST.Stop_nback = cell2mat(rawNumericColumns(:, 63));
subDataSST.StopDur = cell2mat(rawNumericColumns(:, 64));
subDataSST.StopSignalACC = cell2mat(rawNumericColumns(:, 65));
subDataSST.StopSignalCRESP = cell2mat(rawNumericColumns(:, 66));
subDataSST.StopSignalDuration = cell2mat(rawNumericColumns(:, 67));
subDataSST.StopSignalDurationError = cell2mat(rawNumericColumns(:, 68));
subDataSST.StopSignalFinishTime = cell2mat(rawNumericColumns(:, 69));
subDataSST.StopSignalOffsetDelay = cell2mat(rawNumericColumns(:, 70));
subDataSST.StopSignalOffsetTime = cell2mat(rawNumericColumns(:, 71));
subDataSST.StopSignalOnsetDelay = cell2mat(rawNumericColumns(:, 72));
subDataSST.StopSignalOnsetTime = cell2mat(rawNumericColumns(:, 73));
subDataSST.StopSignalOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 74));
subDataSST.StopSignalRESP = cell2mat(rawNumericColumns(:, 75));
subDataSST.StopSignalRT = cell2mat(rawNumericColumns(:, 76));
subDataSST.StopSignalRTTime = cell2mat(rawNumericColumns(:, 77));
subDataSST.StopSignalStartTime = cell2mat(rawNumericColumns(:, 78));
subDataSST.TestListA = cell2mat(rawNumericColumns(:, 79));
subDataSST.TestListACycle = cell2mat(rawNumericColumns(:, 80));
subDataSST.TestListASample = cell2mat(rawNumericColumns(:, 81));
subDataSST.TestListB = cell2mat(rawNumericColumns(:, 82));
subDataSST.TestListBCycle = cell2mat(rawNumericColumns(:, 83));
subDataSST.TestListBSample = cell2mat(rawNumericColumns(:, 84));
subDataSST.TrialCode = cell2mat(rawNumericColumns(:, 85));
subDataSST.Wait4ScannerRTTime = cell2mat(rawNumericColumns(:, 86));
subDataSST.Wait4ScannerBRTTime = cell2mat(rawNumericColumns(:, 87));
subDataSST.Waiting4Scanner = cell2mat(rawNumericColumns(:, 88));
subDataSST.Waiting4ScannerCycle = cell2mat(rawNumericColumns(:, 89));
subDataSST.Waiting4ScannerSample = cell2mat(rawNumericColumns(:, 90));
subDataSST.Waiting4ScannerB = cell2mat(rawNumericColumns(:, 91));
subDataSST.Waiting4ScannerBCycle = cell2mat(rawNumericColumns(:, 92));
subDataSST.Waiting4ScannerBSample = cell2mat(rawNumericColumns(:, 93));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% HYAENE6SST.SessionDate=datenum(HYAENE6SST.SessionDate);
% HYAENE6SST.SessionTime=datenum(HYAENE6SST.SessionTime);

