function sstData = importSST(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   HYAENE6SST = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   HYAENE6SST = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   HYAENE6SST = importfile('2HYAENE6_SST.csv', 3, 368);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/23 13:05:25

%% Initialize variables.
delimiter = {',','\t'};
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,7,9,11,13,14,22,23,26,27,28,32,33,34,35,36,37,38,39,40,41,42,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,81,82,83,84,85,86,87,89,90,91,92,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

dateFormats = {'MM/dd/yyyy', 'HH:mm:ss'};
dateFormatIndex = 1;
blankDates = cell(1,size(raw,2));
anyBlankDates = false(size(raw,1),1);
invalidDates = cell(1,size(raw,2));
anyInvalidDates = false(size(raw,1),1);
for col=[18,20]% Convert the contents of columns with dates to MATLAB datetimes using the specified date format.
    try
        dates{col} = datetime(dataArray{col}, 'Format', dateFormats{col==[18,20]}, 'InputFormat', dateFormats{col==[18,20]}); %#ok<SAGROW>
    catch
        try
            % Handle dates surrounded by quotes
            dataArray{col} = cellfun(@(x) x(2:end-1), dataArray{col}, 'UniformOutput', false);
            dates{col} = datetime(dataArray{col}, 'Format', dateFormats{col==[18,20]}, 'InputFormat', dateFormats{col==[18,20]}); %%#ok<SAGROW>
        catch
            dates{col} = repmat(datetime([NaN NaN NaN]), size(dataArray{col})); %#ok<SAGROW>
        end
    end
    
    dateFormatIndex = dateFormatIndex + 1;
    blankDates{col} = cellfun(@isempty, dataArray{col});
    anyBlankDates = blankDates{col} | anyBlankDates;
    invalidDates{col} = isnan(dates{col}.Hour) - blankDates{col};
    anyInvalidDates = invalidDates{col} | anyInvalidDates;
end
dates = dates(:,[18,20]);
blankDates = blankDates(:,[18,20]);
invalidDates = invalidDates(:,[18,20]);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,7,9,11,13,14,22,23,26,27,28,32,33,34,35,36,37,38,39,40,41,42,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,81,82,83,84,85,86,87,89,90,91,92,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128]);
rawCellColumns = raw(:, [5,6,8,10,12,15,16,17,19,21,24,25,29,30,31,43,44,45,46,47,48,49,50,51,79,80,88,93,97]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
sstData = table;
sstData.ExperimentName = cell2mat(rawNumericColumns(:, 1));
sstData.Subject = cell2mat(rawNumericColumns(:, 2));
sstData.Session = cell2mat(rawNumericColumns(:, 3));
sstData.Allowed = cell2mat(rawNumericColumns(:, 4));
sstData.ClockInformation = rawCellColumns(:, 1);
sstData.DataFileBasename = rawCellColumns(:, 2);
sstData.DisplayRefreshRate = cell2mat(rawNumericColumns(:, 5));
sstData.ExperimentVersion = rawCellColumns(:, 3);
sstData.Group = cell2mat(rawNumericColumns(:, 6));
sstData.Handedness = rawCellColumns(:, 4);
sstData.leftarrow = cell2mat(rawNumericColumns(:, 7));
sstData.NARGUID = rawCellColumns(:, 5);
sstData.RandomSeed = cell2mat(rawNumericColumns(:, 8));
sstData.rightarrow = cell2mat(rawNumericColumns(:, 9));
sstData.RuntimeCapabilities = rawCellColumns(:, 6);
sstData.RuntimeVersion = rawCellColumns(:, 7);
sstData.RuntimeVersionExpected = rawCellColumns(:, 8);
sstData.SessionDate = dates{:, 1};
sstData.SessionStartDateTimeUtc = rawCellColumns(:, 9);
sstData.SessionTime = dates{:, 2};
sstData.StudioVersion = rawCellColumns(:, 10);
sstData.triggercode = cell2mat(rawNumericColumns(:, 10));
sstData.Block = cell2mat(rawNumericColumns(:, 11));
sstData.ProcedureBlock = rawCellColumns(:, 11);
sstData.RunningBlock = rawCellColumns(:, 12);
sstData.TestBlockA = cell2mat(rawNumericColumns(:, 12));
sstData.TestBlockACycle = cell2mat(rawNumericColumns(:, 13));
sstData.TestBlockASample = cell2mat(rawNumericColumns(:, 14));
sstData.TestBlockB = rawCellColumns(:, 13);
sstData.TestBlockBCycle = rawCellColumns(:, 14);
sstData.TestBlockBSample = rawCellColumns(:, 15);
sstData.Trial = cell2mat(rawNumericColumns(:, 15));
sstData.BeginFixDuration = cell2mat(rawNumericColumns(:, 16));
sstData.BeginFixDurationError = cell2mat(rawNumericColumns(:, 17));
sstData.BeginFixFinishTime = cell2mat(rawNumericColumns(:, 18));
sstData.BeginFixOffsetDelay = cell2mat(rawNumericColumns(:, 19));
sstData.BeginFixOffsetTime = cell2mat(rawNumericColumns(:, 20));
sstData.BeginFixOnsetDelay = cell2mat(rawNumericColumns(:, 21));
sstData.BeginFixOnsetTime = cell2mat(rawNumericColumns(:, 22));
sstData.BeginFixOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 23));
sstData.BeginFixStartTime = cell2mat(rawNumericColumns(:, 24));
sstData.CorrectAnswer = cell2mat(rawNumericColumns(:, 25));
sstData.EndFixDuration = rawCellColumns(:, 16);
sstData.EndFixDurationError = rawCellColumns(:, 17);
sstData.EndFixFinishTime = rawCellColumns(:, 18);
sstData.EndFixOffsetDelay = rawCellColumns(:, 19);
sstData.EndFixOffsetTime = rawCellColumns(:, 20);
sstData.EndFixOnsetDelay = rawCellColumns(:, 21);
sstData.EndFixOnsetTime = rawCellColumns(:, 22);
sstData.EndFixOnsetToOnsetTime = rawCellColumns(:, 23);
sstData.EndFixStartTime = rawCellColumns(:, 24);
sstData.FixDuration = cell2mat(rawNumericColumns(:, 26));
sstData.FixDurationError = cell2mat(rawNumericColumns(:, 27));
sstData.FixFinishTime = cell2mat(rawNumericColumns(:, 28));
sstData.FixOffsetDelay = cell2mat(rawNumericColumns(:, 29));
sstData.FixOffsetTime = cell2mat(rawNumericColumns(:, 30));
sstData.FixOnsetDelay = cell2mat(rawNumericColumns(:, 31));
sstData.FixOnsetTime = cell2mat(rawNumericColumns(:, 32));
sstData.FixOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 33));
sstData.FixRESP = cell2mat(rawNumericColumns(:, 34));
sstData.FixRT = cell2mat(rawNumericColumns(:, 35));
sstData.FixStartTime = cell2mat(rawNumericColumns(:, 36));
sstData.FixDur = cell2mat(rawNumericColumns(:, 37));
sstData.GoACC = cell2mat(rawNumericColumns(:, 38));
sstData.GoCRESP = cell2mat(rawNumericColumns(:, 39));
sstData.GoDuration = cell2mat(rawNumericColumns(:, 40));
sstData.GoDurationError = cell2mat(rawNumericColumns(:, 41));
sstData.GoFinishTime = cell2mat(rawNumericColumns(:, 42));
sstData.GoOffsetDelay = cell2mat(rawNumericColumns(:, 43));
sstData.GoOffsetTime = cell2mat(rawNumericColumns(:, 44));
sstData.GoOnsetDelay = cell2mat(rawNumericColumns(:, 45));
sstData.GoOnsetTime = cell2mat(rawNumericColumns(:, 46));
sstData.GoOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 47));
sstData.GoRESP = cell2mat(rawNumericColumns(:, 48));
sstData.GoRT = cell2mat(rawNumericColumns(:, 49));
sstData.GoRTTime = cell2mat(rawNumericColumns(:, 50));
sstData.GoStartTime = cell2mat(rawNumericColumns(:, 51));
sstData.Jitter = cell2mat(rawNumericColumns(:, 52));
sstData.ProcedureTrial = rawCellColumns(:, 25);
sstData.RunningTrial = rawCellColumns(:, 26);
sstData.SiemensPadOffsetDelay = cell2mat(rawNumericColumns(:, 53));
sstData.SiemensPadOffsetTime = cell2mat(rawNumericColumns(:, 54));
sstData.SiemensPadOnsetDelay = cell2mat(rawNumericColumns(:, 55));
sstData.SiemensPadOnsetTime = cell2mat(rawNumericColumns(:, 56));
sstData.SiemensPadOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 57));
sstData.SiemensPadRTTime = cell2mat(rawNumericColumns(:, 58));
sstData.SSDACC = cell2mat(rawNumericColumns(:, 59));
sstData.SSDCRESP = rawCellColumns(:, 27);
sstData.SSDDurationError = cell2mat(rawNumericColumns(:, 60));
sstData.SSDOnsetDelay = cell2mat(rawNumericColumns(:, 61));
sstData.SSDOnsetTime = cell2mat(rawNumericColumns(:, 62));
sstData.SSDOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 63));
sstData.SSDRESP = rawCellColumns(:, 28);
sstData.SSDRT = cell2mat(rawNumericColumns(:, 64));
sstData.SSDRTTime = cell2mat(rawNumericColumns(:, 65));
sstData.SSDDur = cell2mat(rawNumericColumns(:, 66));
sstData.Stimulus = rawCellColumns(:, 29);
sstData.Stop_nback = cell2mat(rawNumericColumns(:, 67));
sstData.StopDur = cell2mat(rawNumericColumns(:, 68));
sstData.StopSignalACC = cell2mat(rawNumericColumns(:, 69));
sstData.StopSignalCRESP = cell2mat(rawNumericColumns(:, 70));
sstData.StopSignalDuration = cell2mat(rawNumericColumns(:, 71));
sstData.StopSignalDurationError = cell2mat(rawNumericColumns(:, 72));
sstData.StopSignalFinishTime = cell2mat(rawNumericColumns(:, 73));
sstData.StopSignalOffsetDelay = cell2mat(rawNumericColumns(:, 74));
sstData.StopSignalOffsetTime = cell2mat(rawNumericColumns(:, 75));
sstData.StopSignalOnsetDelay = cell2mat(rawNumericColumns(:, 76));
sstData.StopSignalOnsetTime = cell2mat(rawNumericColumns(:, 77));
sstData.StopSignalOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 78));
sstData.StopSignalRESP = cell2mat(rawNumericColumns(:, 79));
sstData.StopSignalRT = cell2mat(rawNumericColumns(:, 80));
sstData.StopSignalRTTime = cell2mat(rawNumericColumns(:, 81));
sstData.StopSignalStartTime = cell2mat(rawNumericColumns(:, 82));
sstData.TestListA = cell2mat(rawNumericColumns(:, 83));
sstData.TestListACycle = cell2mat(rawNumericColumns(:, 84));
sstData.TestListASample = cell2mat(rawNumericColumns(:, 85));
sstData.TestListB = cell2mat(rawNumericColumns(:, 86));
sstData.TestListBCycle = cell2mat(rawNumericColumns(:, 87));
sstData.TestListBSample = cell2mat(rawNumericColumns(:, 88));
sstData.TrialCode = cell2mat(rawNumericColumns(:, 89));
sstData.Wait4ScannerRTTime = cell2mat(rawNumericColumns(:, 90));
sstData.Wait4ScannerBRTTime = cell2mat(rawNumericColumns(:, 91));
sstData.Waiting4Scanner = cell2mat(rawNumericColumns(:, 92));
sstData.Waiting4ScannerCycle = cell2mat(rawNumericColumns(:, 93));
sstData.Waiting4ScannerSample = cell2mat(rawNumericColumns(:, 94));
sstData.Waiting4ScannerB = cell2mat(rawNumericColumns(:, 95));
sstData.Waiting4ScannerBCycle = cell2mat(rawNumericColumns(:, 96));
sstData.Waiting4ScannerBSample = cell2mat(rawNumericColumns(:, 97));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% HYAENE6SST.SessionDate=datenum(HYAENE6SST.SessionDate);
% HYAENE6SST.SessionTime=datenum(HYAENE6SST.SessionTime);

