function subjDataMID = importSubjDataMIDtableDecrepit(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   NDARINVHMNN9G5JMID = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   NDARINVHMNN9G5JMID = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   NDARINVHMNN9G5JMID = importfile('NDAR_INVHMNN9G5J_MID.csv', 2, 106);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/16 13:22:54

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);

if size(raw,1)<105 % Task was aborted early
    subjDataMID = false;
    return
end
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,5,6,11,12,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,33,34,35,36,37,38,39,40,41,42,43,44,45,46,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

dateFormats = {'MM/dd/yyyy', 'MM/dd/yyyy HH:mm', 'HH:mm:ss'};
dateFormatIndex = 1;
blankDates = cell(1,size(raw,2));
anyBlankDates = false(size(raw,1),1);
invalidDates = cell(1,size(raw,2));
anyInvalidDates = false(size(raw,1),1);
for col=[13,14,15]% Convert the contents of columns with dates to MATLAB datetimes using the specified date format.
    try
        dates{col} = datetime(dataArray{col}, 'Format', dateFormats{col==[13,14,15]}, 'InputFormat', dateFormats{col==[13,14,15]}); %#ok<SAGROW>
    catch
        try
            % Handle dates surrounded by quotes
            dataArray{col} = cellfun(@(x) x(2:end-1), dataArray{col}, 'UniformOutput', false);
            dates{col} = datetime(dataArray{col}, 'Format', dateFormats{col==[13,14,15]}, 'InputFormat', dateFormats{col==[13,14,15]}); %%#ok<SAGROW>
        catch
            dates{col} = repmat(datetime([NaN NaN NaN]), size(dataArray{col})); %#ok<SAGROW>
        end
    end
    
    dateFormatIndex = dateFormatIndex + 1;
    blankDates{col} = cellfun(@isempty, dataArray{col});
    anyBlankDates = blankDates{col} | anyBlankDates;
    invalidDates{col} = isnan(dates{col}.Hour) - blankDates{col};
    anyInvalidDates = invalidDates{col} | anyInvalidDates;
end
dates = dates(:,[13,14,15]);
blankDates = blankDates(:,[13,14,15]);
invalidDates = invalidDates(:,[13,14,15]);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,5,6,11,12,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,33,34,35,36,37,38,39,40,41,42,43,44,45,46,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129]);
rawCellColumns = raw(:, [4,7,8,9,10,31,32,47,48,69,70,97]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
subjDataMID = table;
subjDataMID.ExperimentName = cell2mat(rawNumericColumns(:, 1));
subjDataMID.Subject = cell2mat(rawNumericColumns(:, 2));
subjDataMID.Session = cell2mat(rawNumericColumns(:, 3));
subjDataMID.DataFileBasename = rawCellColumns(:, 1);
subjDataMID.DisplayRefreshRate = cell2mat(rawNumericColumns(:, 4));
subjDataMID.Group = cell2mat(rawNumericColumns(:, 5));
subjDataMID.Handedness = rawCellColumns(:, 2);
subjDataMID.ImgPath = rawCellColumns(:, 3);
subjDataMID.MIDVERSION = rawCellColumns(:, 4);
subjDataMID.NARGUID = rawCellColumns(:, 5);
subjDataMID.PracticeRT = cell2mat(rawNumericColumns(:, 6));
subjDataMID.RandomSeed = cell2mat(rawNumericColumns(:, 7));
subjDataMID.SessionDate = dates{:, 1};
subjDataMID.SessionStartDateTimeUtc = dates{:, 2};
subjDataMID.SessionTime = dates{:, 3};
subjDataMID.Block = cell2mat(rawNumericColumns(:, 8));
subjDataMID.BlockList = cell2mat(rawNumericColumns(:, 9));
subjDataMID.BlockListCycle = cell2mat(rawNumericColumns(:, 10));
subjDataMID.BlockListSample = cell2mat(rawNumericColumns(:, 11));
subjDataMID.BlockTitle = cell2mat(rawNumericColumns(:, 12));
subjDataMID.EndFixDuration = cell2mat(rawNumericColumns(:, 13));
subjDataMID.EndFixDurationError = cell2mat(rawNumericColumns(:, 14));
subjDataMID.EndFixFinishTime = cell2mat(rawNumericColumns(:, 15));
subjDataMID.EndFixOffsetDelay = cell2mat(rawNumericColumns(:, 16));
subjDataMID.EndFixOffsetTime = cell2mat(rawNumericColumns(:, 17));
subjDataMID.EndFixOnsetDelay = cell2mat(rawNumericColumns(:, 18));
subjDataMID.EndFixOnsetTime = cell2mat(rawNumericColumns(:, 19));
subjDataMID.EndFixOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 20));
subjDataMID.EndFixStartTime = cell2mat(rawNumericColumns(:, 21));
subjDataMID.ListName = cell2mat(rawNumericColumns(:, 22));
subjDataMID.ProcedureBlock = rawCellColumns(:, 6);
subjDataMID.RunningBlock = rawCellColumns(:, 7);
subjDataMID.Trial = cell2mat(rawNumericColumns(:, 23));
subjDataMID.GetReadyRTTime = cell2mat(rawNumericColumns(:, 24));
subjDataMID.PeriodList = cell2mat(rawNumericColumns(:, 25));
subjDataMID.PeriodListCycle = cell2mat(rawNumericColumns(:, 26));
subjDataMID.PeriodListSample = cell2mat(rawNumericColumns(:, 27));
subjDataMID.PrepTimeDuration = cell2mat(rawNumericColumns(:, 28));
subjDataMID.PrepTimeDurationError = cell2mat(rawNumericColumns(:, 29));
subjDataMID.PrepTimeFinishTime = cell2mat(rawNumericColumns(:, 30));
subjDataMID.PrepTimeOffsetDelay = cell2mat(rawNumericColumns(:, 31));
subjDataMID.PrepTimeOffsetTime = cell2mat(rawNumericColumns(:, 32));
subjDataMID.PrepTimeOnsetDelay = cell2mat(rawNumericColumns(:, 33));
subjDataMID.PrepTimeOnsetTime = cell2mat(rawNumericColumns(:, 34));
subjDataMID.PrepTimeOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 35));
subjDataMID.PrepTimeStartTime = cell2mat(rawNumericColumns(:, 36));
subjDataMID.ProcedureTrial = rawCellColumns(:, 8);
subjDataMID.RunningTrial = rawCellColumns(:, 9);
subjDataMID.SiemensPadOffsetDelay = cell2mat(rawNumericColumns(:, 37));
subjDataMID.SiemensPadOffsetTime = cell2mat(rawNumericColumns(:, 38));
subjDataMID.SiemensPadOnsetDelay = cell2mat(rawNumericColumns(:, 39));
subjDataMID.SiemensPadOnsetTime = cell2mat(rawNumericColumns(:, 40));
subjDataMID.SiemensPadOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 41));
subjDataMID.SiemensPadRTTime = cell2mat(rawNumericColumns(:, 42));
subjDataMID.Waiting4Scanner = cell2mat(rawNumericColumns(:, 43));
subjDataMID.Waiting4ScannerCycle = cell2mat(rawNumericColumns(:, 44));
subjDataMID.Waiting4ScannerSample = cell2mat(rawNumericColumns(:, 45));
subjDataMID.SubTrial = cell2mat(rawNumericColumns(:, 46));
subjDataMID.AnticipationDuration = cell2mat(rawNumericColumns(:, 47));
subjDataMID.AnticipationDurationError = cell2mat(rawNumericColumns(:, 48));
subjDataMID.AnticipationFinishTime = cell2mat(rawNumericColumns(:, 49));
subjDataMID.AnticipationOffsetDelay = cell2mat(rawNumericColumns(:, 50));
subjDataMID.AnticipationOffsetTime = cell2mat(rawNumericColumns(:, 51));
subjDataMID.AnticipationOnsetDelay = cell2mat(rawNumericColumns(:, 52));
subjDataMID.AnticipationOnsetTime = cell2mat(rawNumericColumns(:, 53));
subjDataMID.AnticipationOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 54));
subjDataMID.AnticipationStartTime = cell2mat(rawNumericColumns(:, 55));
subjDataMID.AnticipationDuration1 = cell2mat(rawNumericColumns(:, 56));
subjDataMID.Condition = rawCellColumns(:, 10);
subjDataMID.Cue = rawCellColumns(:, 11);
subjDataMID.CueCustomOnsetTime = cell2mat(rawNumericColumns(:, 57));
subjDataMID.CueDuration = cell2mat(rawNumericColumns(:, 58));
subjDataMID.CueDurationError = cell2mat(rawNumericColumns(:, 59));
subjDataMID.CueFinishTime = cell2mat(rawNumericColumns(:, 60));
subjDataMID.CueOffsetDelay = cell2mat(rawNumericColumns(:, 61));
subjDataMID.CueOffsetTime = cell2mat(rawNumericColumns(:, 62));
subjDataMID.CueOnsetDelay = cell2mat(rawNumericColumns(:, 63));
subjDataMID.CueOnsetTime = cell2mat(rawNumericColumns(:, 64));
subjDataMID.CueOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 65));
subjDataMID.CueStartTime = cell2mat(rawNumericColumns(:, 66));
subjDataMID.FeedbackDuration = cell2mat(rawNumericColumns(:, 67));
subjDataMID.FeedbackDurationError = cell2mat(rawNumericColumns(:, 68));
subjDataMID.FeedbackFinishTime = cell2mat(rawNumericColumns(:, 69));
subjDataMID.FeedbackOffsetDelay = cell2mat(rawNumericColumns(:, 70));
subjDataMID.FeedbackOffsetTime = cell2mat(rawNumericColumns(:, 71));
subjDataMID.FeedbackOnsetDelay = cell2mat(rawNumericColumns(:, 72));
subjDataMID.FeedbackOnsetTime = cell2mat(rawNumericColumns(:, 73));
subjDataMID.FeedbackOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 74));
subjDataMID.FeedbackStartTime = cell2mat(rawNumericColumns(:, 75));
subjDataMID.FeedbackDuration1 = cell2mat(rawNumericColumns(:, 76));
subjDataMID.meanrt = cell2mat(rawNumericColumns(:, 77));
subjDataMID.moneyamt = cell2mat(rawNumericColumns(:, 78));
subjDataMID.percentacc = cell2mat(rawNumericColumns(:, 79));
subjDataMID.prbacc = cell2mat(rawNumericColumns(:, 80));
subjDataMID.prbresp = cell2mat(rawNumericColumns(:, 81));
subjDataMID.prbrt = cell2mat(rawNumericColumns(:, 82));
subjDataMID.Probe = rawCellColumns(:, 12);
subjDataMID.ProbeDuration = cell2mat(rawNumericColumns(:, 83));
subjDataMID.ProbeDurationError = cell2mat(rawNumericColumns(:, 84));
subjDataMID.ProbeFinishTime = cell2mat(rawNumericColumns(:, 85));
subjDataMID.ProbeOffsetDelay = cell2mat(rawNumericColumns(:, 86));
subjDataMID.ProbeOffsetTime = cell2mat(rawNumericColumns(:, 87));
subjDataMID.ProbeOnsetDelay = cell2mat(rawNumericColumns(:, 88));
subjDataMID.ProbeOnsetTime = cell2mat(rawNumericColumns(:, 89));
subjDataMID.ProbeOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 90));
subjDataMID.ProbeRESP = cell2mat(rawNumericColumns(:, 91));
subjDataMID.ProbeRT = cell2mat(rawNumericColumns(:, 92));
subjDataMID.ProbeRTTime = cell2mat(rawNumericColumns(:, 93));
subjDataMID.ProbeStartTime = cell2mat(rawNumericColumns(:, 94));
subjDataMID.ProbeTime = cell2mat(rawNumericColumns(:, 95));
subjDataMID.ProcedureSubTrial = cell2mat(rawNumericColumns(:, 96));
subjDataMID.ResponseCheck = cell2mat(rawNumericColumns(:, 97));
subjDataMID.Result = cell2mat(rawNumericColumns(:, 98));
subjDataMID.RunList = cell2mat(rawNumericColumns(:, 99));
subjDataMID.RunListCycle = cell2mat(rawNumericColumns(:, 100));
subjDataMID.RunListSample = cell2mat(rawNumericColumns(:, 101));
subjDataMID.RunMoney = cell2mat(rawNumericColumns(:, 102));
subjDataMID.RunningSubTrial = cell2mat(rawNumericColumns(:, 103));
subjDataMID.TextDisplay1Duration = cell2mat(rawNumericColumns(:, 104));
subjDataMID.TextDisplay1DurationError = cell2mat(rawNumericColumns(:, 105));
subjDataMID.TextDisplay1FinishTime = cell2mat(rawNumericColumns(:, 106));
subjDataMID.TextDisplay1OffsetDelay = cell2mat(rawNumericColumns(:, 107));
subjDataMID.TextDisplay1OffsetTime = cell2mat(rawNumericColumns(:, 108));
subjDataMID.TextDisplay1OnsetDelay = cell2mat(rawNumericColumns(:, 109));
subjDataMID.TextDisplay1OnsetTime = cell2mat(rawNumericColumns(:, 110));
subjDataMID.TextDisplay1OnsetToOnsetTime = cell2mat(rawNumericColumns(:, 111));
subjDataMID.TextDisplay1StartTime = cell2mat(rawNumericColumns(:, 112));
subjDataMID.TimeVersion16 = cell2mat(rawNumericColumns(:, 113));
subjDataMID.TimeVersion5 = cell2mat(rawNumericColumns(:, 114));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% NDARINVHMNN9G5JMID.SessionDate=datenum(NDARINVHMNN9G5JMID.SessionDate);
% NDARINVHMNN9G5JMID.SessionStartDateTimeUtc=datenum(NDARINVHMNN9G5JMID.SessionStartDateTimeUtc);NDARINVHMNN9G5JMID.SessionTime=datenum(NDARINVHMNN9G5JMID.SessionTime);

