function NDARINV81W1WMVMMID = importSubjDataMIDBehavtable(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   NDARINV81W1WMVMMID = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   NDARINV81W1WMVMMID = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   NDARINV81W1WMVMMID = importfile('NDAR_INV81W1WMVM_MID.txt', 2, 106);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/16 11:39:20

%% Initialize variables.
delimiter = {'\t',','};
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,7,9,12,13,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,39,40,41,42,43,44,45,46,47,48,49,50,51,52,55,56,57,58,59,60,61,62,63,64,65,66,67,68,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using the
% specified date format.
try
    dates{19} = datetime(dataArray{19}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{19} = cellfun(@(x) x(2:end-1), dataArray{19}, 'UniformOutput', false);
        dates{19} = datetime(dataArray{19}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
    catch
        dates{19} = repmat(datetime([NaN NaN NaN]), size(dataArray{19}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{19});
anyInvalidDates = isnan(dates{19}.Hour) - anyBlankDates;
dates = dates(:,19);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,7,9,12,13,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,39,40,41,42,43,44,45,46,47,48,49,50,51,52,55,56,57,58,59,60,61,62,63,64,65,66,67,68,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129]);
rawCellColumns = raw(:, [4,5,6,8,10,11,14,15,16,17,18,20,22,37,38,53,54,69,70,95,97]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
NDARINV81W1WMVMMID = table;
NDARINV81W1WMVMMID.ExperimentName = cell2mat(rawNumericColumns(:, 1));
NDARINV81W1WMVMMID.Subject = cell2mat(rawNumericColumns(:, 2));
NDARINV81W1WMVMMID.Session = cell2mat(rawNumericColumns(:, 3));
NDARINV81W1WMVMMID.Allowed = rawCellColumns(:, 1);
NDARINV81W1WMVMMID.ClockInformation = rawCellColumns(:, 2);
NDARINV81W1WMVMMID.DataFileBasename = rawCellColumns(:, 3);
NDARINV81W1WMVMMID.DisplayRefreshRate = cell2mat(rawNumericColumns(:, 4));
NDARINV81W1WMVMMID.ExperimentVersion = rawCellColumns(:, 4);
NDARINV81W1WMVMMID.Group = cell2mat(rawNumericColumns(:, 5));
NDARINV81W1WMVMMID.Handedness = rawCellColumns(:, 5);
NDARINV81W1WMVMMID.NARGUID = rawCellColumns(:, 6);
NDARINV81W1WMVMMID.PracticeRT = cell2mat(rawNumericColumns(:, 6));
NDARINV81W1WMVMMID.RandomSeed = cell2mat(rawNumericColumns(:, 7));
NDARINV81W1WMVMMID.RuntimeCapabilities = rawCellColumns(:, 7);
NDARINV81W1WMVMMID.RuntimeVersion = rawCellColumns(:, 8);
NDARINV81W1WMVMMID.RuntimeVersionExpected = rawCellColumns(:, 9);
NDARINV81W1WMVMMID.SessionDate = rawCellColumns(:, 10);
NDARINV81W1WMVMMID.SessionStartDateTimeUtc = rawCellColumns(:, 11);
NDARINV81W1WMVMMID.SessionTime = dates{:, 1};
NDARINV81W1WMVMMID.StudioVersion = rawCellColumns(:, 12);
NDARINV81W1WMVMMID.TrialOrder = cell2mat(rawNumericColumns(:, 8));
NDARINV81W1WMVMMID.triggercode = rawCellColumns(:, 13);
NDARINV81W1WMVMMID.Block = cell2mat(rawNumericColumns(:, 9));
NDARINV81W1WMVMMID.BlockList = cell2mat(rawNumericColumns(:, 10));
NDARINV81W1WMVMMID.BlockListCycle = cell2mat(rawNumericColumns(:, 11));
NDARINV81W1WMVMMID.BlockListSample = cell2mat(rawNumericColumns(:, 12));
NDARINV81W1WMVMMID.BlockTitle = cell2mat(rawNumericColumns(:, 13));
NDARINV81W1WMVMMID.EndFixDuration = cell2mat(rawNumericColumns(:, 14));
NDARINV81W1WMVMMID.EndFixDurationError = cell2mat(rawNumericColumns(:, 15));
NDARINV81W1WMVMMID.EndFixFinishTime = cell2mat(rawNumericColumns(:, 16));
NDARINV81W1WMVMMID.EndFixOffsetDelay = cell2mat(rawNumericColumns(:, 17));
NDARINV81W1WMVMMID.EndFixOffsetTime = cell2mat(rawNumericColumns(:, 18));
NDARINV81W1WMVMMID.EndFixOnsetDelay = cell2mat(rawNumericColumns(:, 19));
NDARINV81W1WMVMMID.EndFixOnsetTime = cell2mat(rawNumericColumns(:, 20));
NDARINV81W1WMVMMID.EndFixOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 21));
NDARINV81W1WMVMMID.EndFixStartTime = cell2mat(rawNumericColumns(:, 22));
NDARINV81W1WMVMMID.ProcedureBlock = rawCellColumns(:, 14);
NDARINV81W1WMVMMID.RunningBlock = rawCellColumns(:, 15);
NDARINV81W1WMVMMID.Trial = cell2mat(rawNumericColumns(:, 23));
NDARINV81W1WMVMMID.GetReadyRTTime = cell2mat(rawNumericColumns(:, 24));
NDARINV81W1WMVMMID.PeriodList = cell2mat(rawNumericColumns(:, 25));
NDARINV81W1WMVMMID.PeriodListCycle = cell2mat(rawNumericColumns(:, 26));
NDARINV81W1WMVMMID.PeriodListSample = cell2mat(rawNumericColumns(:, 27));
NDARINV81W1WMVMMID.PrepTimeDuration = cell2mat(rawNumericColumns(:, 28));
NDARINV81W1WMVMMID.PrepTimeDurationError = cell2mat(rawNumericColumns(:, 29));
NDARINV81W1WMVMMID.PrepTimeFinishTime = cell2mat(rawNumericColumns(:, 30));
NDARINV81W1WMVMMID.PrepTimeOffsetDelay = cell2mat(rawNumericColumns(:, 31));
NDARINV81W1WMVMMID.PrepTimeOffsetTime = cell2mat(rawNumericColumns(:, 32));
NDARINV81W1WMVMMID.PrepTimeOnsetDelay = cell2mat(rawNumericColumns(:, 33));
NDARINV81W1WMVMMID.PrepTimeOnsetTime = cell2mat(rawNumericColumns(:, 34));
NDARINV81W1WMVMMID.PrepTimeOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 35));
NDARINV81W1WMVMMID.PrepTimeStartTime = cell2mat(rawNumericColumns(:, 36));
NDARINV81W1WMVMMID.ProcedureTrial = rawCellColumns(:, 16);
NDARINV81W1WMVMMID.RunningTrial = rawCellColumns(:, 17);
NDARINV81W1WMVMMID.Waiting4Scanner = cell2mat(rawNumericColumns(:, 37));
NDARINV81W1WMVMMID.Waiting4ScannerCycle = cell2mat(rawNumericColumns(:, 38));
NDARINV81W1WMVMMID.Waiting4ScannerSample = cell2mat(rawNumericColumns(:, 39));
NDARINV81W1WMVMMID.SubTrial = cell2mat(rawNumericColumns(:, 40));
NDARINV81W1WMVMMID.AnticipationDuration = cell2mat(rawNumericColumns(:, 41));
NDARINV81W1WMVMMID.AnticipationDurationError = cell2mat(rawNumericColumns(:, 42));
NDARINV81W1WMVMMID.AnticipationFinishTime = cell2mat(rawNumericColumns(:, 43));
NDARINV81W1WMVMMID.AnticipationOffsetDelay = cell2mat(rawNumericColumns(:, 44));
NDARINV81W1WMVMMID.AnticipationOffsetTime = cell2mat(rawNumericColumns(:, 45));
NDARINV81W1WMVMMID.AnticipationOnsetDelay = cell2mat(rawNumericColumns(:, 46));
NDARINV81W1WMVMMID.AnticipationOnsetTime = cell2mat(rawNumericColumns(:, 47));
NDARINV81W1WMVMMID.AnticipationOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 48));
NDARINV81W1WMVMMID.AnticipationStartTime = cell2mat(rawNumericColumns(:, 49));
NDARINV81W1WMVMMID.AnticipationDuration1 = cell2mat(rawNumericColumns(:, 50));
NDARINV81W1WMVMMID.Condition = rawCellColumns(:, 18);
NDARINV81W1WMVMMID.Cue = rawCellColumns(:, 19);
NDARINV81W1WMVMMID.CueCustomOnsetTime = cell2mat(rawNumericColumns(:, 51));
NDARINV81W1WMVMMID.CueDuration = cell2mat(rawNumericColumns(:, 52));
NDARINV81W1WMVMMID.CueDurationError = cell2mat(rawNumericColumns(:, 53));
NDARINV81W1WMVMMID.CueFinishTime = cell2mat(rawNumericColumns(:, 54));
NDARINV81W1WMVMMID.CueOffsetDelay = cell2mat(rawNumericColumns(:, 55));
NDARINV81W1WMVMMID.CueOffsetTime = cell2mat(rawNumericColumns(:, 56));
NDARINV81W1WMVMMID.CueOnsetDelay = cell2mat(rawNumericColumns(:, 57));
NDARINV81W1WMVMMID.CueOnsetTime = cell2mat(rawNumericColumns(:, 58));
NDARINV81W1WMVMMID.CueOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 59));
NDARINV81W1WMVMMID.CueStartTime = cell2mat(rawNumericColumns(:, 60));
NDARINV81W1WMVMMID.FeedbackDuration = cell2mat(rawNumericColumns(:, 61));
NDARINV81W1WMVMMID.FeedbackDurationError = cell2mat(rawNumericColumns(:, 62));
NDARINV81W1WMVMMID.FeedbackFinishTime = cell2mat(rawNumericColumns(:, 63));
NDARINV81W1WMVMMID.FeedbackOffsetDelay = cell2mat(rawNumericColumns(:, 64));
NDARINV81W1WMVMMID.FeedbackOffsetTime = cell2mat(rawNumericColumns(:, 65));
NDARINV81W1WMVMMID.FeedbackOnsetDelay = cell2mat(rawNumericColumns(:, 66));
NDARINV81W1WMVMMID.FeedbackOnsetTime = cell2mat(rawNumericColumns(:, 67));
NDARINV81W1WMVMMID.FeedbackOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 68));
NDARINV81W1WMVMMID.FeedbackStartTime = cell2mat(rawNumericColumns(:, 69));
NDARINV81W1WMVMMID.FeedbackDuration1 = cell2mat(rawNumericColumns(:, 70));
NDARINV81W1WMVMMID.meanrt = cell2mat(rawNumericColumns(:, 71));
NDARINV81W1WMVMMID.moneyamt = cell2mat(rawNumericColumns(:, 72));
NDARINV81W1WMVMMID.percentacc = cell2mat(rawNumericColumns(:, 73));
NDARINV81W1WMVMMID.prbacc = cell2mat(rawNumericColumns(:, 74));
NDARINV81W1WMVMMID.prbresp = rawCellColumns(:, 20);
NDARINV81W1WMVMMID.prbrt = cell2mat(rawNumericColumns(:, 75));
NDARINV81W1WMVMMID.Probe = rawCellColumns(:, 21);
NDARINV81W1WMVMMID.ProbeDuration = cell2mat(rawNumericColumns(:, 76));
NDARINV81W1WMVMMID.ProbeDurationError = cell2mat(rawNumericColumns(:, 77));
NDARINV81W1WMVMMID.ProbeFinishTime = cell2mat(rawNumericColumns(:, 78));
NDARINV81W1WMVMMID.ProbeOffsetDelay = cell2mat(rawNumericColumns(:, 79));
NDARINV81W1WMVMMID.ProbeOffsetTime = cell2mat(rawNumericColumns(:, 80));
NDARINV81W1WMVMMID.ProbeOnsetDelay = cell2mat(rawNumericColumns(:, 81));
NDARINV81W1WMVMMID.ProbeOnsetTime = cell2mat(rawNumericColumns(:, 82));
NDARINV81W1WMVMMID.ProbeOnsetToOnsetTime = cell2mat(rawNumericColumns(:, 83));
NDARINV81W1WMVMMID.ProbeRESP = cell2mat(rawNumericColumns(:, 84));
NDARINV81W1WMVMMID.ProbeRT = cell2mat(rawNumericColumns(:, 85));
NDARINV81W1WMVMMID.ProbeRTTime = cell2mat(rawNumericColumns(:, 86));
NDARINV81W1WMVMMID.ProbeStartTime = cell2mat(rawNumericColumns(:, 87));
NDARINV81W1WMVMMID.ProbeTime = cell2mat(rawNumericColumns(:, 88));
NDARINV81W1WMVMMID.ProcedureSubTrial = cell2mat(rawNumericColumns(:, 89));
NDARINV81W1WMVMMID.ResponseCheck = cell2mat(rawNumericColumns(:, 90));
NDARINV81W1WMVMMID.Result = cell2mat(rawNumericColumns(:, 91));
NDARINV81W1WMVMMID.RunList = cell2mat(rawNumericColumns(:, 92));
NDARINV81W1WMVMMID.RunListCycle = cell2mat(rawNumericColumns(:, 93));
NDARINV81W1WMVMMID.RunListSample = cell2mat(rawNumericColumns(:, 94));
NDARINV81W1WMVMMID.RunMoney = cell2mat(rawNumericColumns(:, 95));
NDARINV81W1WMVMMID.RunningSubTrial = cell2mat(rawNumericColumns(:, 96));
NDARINV81W1WMVMMID.TextDisplay1Duration = cell2mat(rawNumericColumns(:, 97));
NDARINV81W1WMVMMID.TextDisplay1DurationError = cell2mat(rawNumericColumns(:, 98));
NDARINV81W1WMVMMID.TextDisplay1FinishTime = cell2mat(rawNumericColumns(:, 99));
NDARINV81W1WMVMMID.TextDisplay1OffsetDelay = cell2mat(rawNumericColumns(:, 100));
NDARINV81W1WMVMMID.TextDisplay1OffsetTime = cell2mat(rawNumericColumns(:, 101));
NDARINV81W1WMVMMID.TextDisplay1OnsetDelay = cell2mat(rawNumericColumns(:, 102));
NDARINV81W1WMVMMID.TextDisplay1OnsetTime = cell2mat(rawNumericColumns(:, 103));
NDARINV81W1WMVMMID.TextDisplay1OnsetToOnsetTime = cell2mat(rawNumericColumns(:, 104));
NDARINV81W1WMVMMID.TextDisplay1StartTime = cell2mat(rawNumericColumns(:, 105));
NDARINV81W1WMVMMID.TimeVersion14 = cell2mat(rawNumericColumns(:, 106));
NDARINV81W1WMVMMID.TimeVersion9 = cell2mat(rawNumericColumns(:, 107));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% NDARINV81W1WMVMMID.SessionTime=datenum(NDARINV81W1WMVMMID.SessionTime);

